swig: Main.cpp swigh.cpp swig.cpp swigs.cpp module.cpp
	g++ -Wall -Wpedantic -std=c++17 -o Swig Main.cpp swigh.cpp swig.cpp swigs.cpp module.cpp
swigWindows: Main.cpp swigh.cpp swig.cpp swigs.cpp module.cpp
	x86_64-w64-mingw32-g++ -Wall -Wpedantic -std=c++17 -o Swig.exe Main.cpp swigh.cpp swig.cpp swigs.cpp module.cpp
