<div class = "list" style = "font-family:'Courier New'; overflow: auto; background-color: rgb(29, 29, 29); color: rgb(255, 255, 255); border-color: black; padding: 10px; border-style: solid; border-radius: 15px; width: 100px; height: 200px; display: inline-block;">
	<div>
		<p><h5>swag</h5></p>
		<p><h5>drag</h5></p>
		<p><h5>bag</h5></p>
		<p><h5>gag</h5></p>
		<p><h5>lag</h5></p>
		<p><h5>mag</h5></p>
		<p><h5>sag</h5></p>
		<p><h5>jag</h5></p>
		<p><h5>wag</h5></p>
		<p><h5>rag</h5></p>
		<p><h5>nag</h5></p>
		<p><h5>zag</h5></p>
		<p><h5>hag</h5></p>
	</div>
</div>
<style>
	.list::-webkit-scrollbar-thumb:hover {
  background: #555; 
  width: 25px;
  border-radius: 20px;
}
.list::-webkit-scrollbar-thumb {
  background: #888;
  border-radius: 10px;
}
.list::-webkit-scrollbar-track {
  background: #000000;
  border-radius: 10px;
  width: 25px;
}
.list::-webkit-scrollbar {
  border-radius: 10px;
  width: 25px;
}
</style>