#div style[font-family<sansserif> border-color<hotpink> width<300px>text-align<center>background-color<pink>border-style<solid> border-radius<20px>]:
	#h1:
	LOGIN
Username `: 
	#input style[border-color<hotpink> width<230px> border-radius<5px> padding<10px> margin<10px>]:
Password `: 
	#input style[border-color<hotpink> width<230px> border-radius<5px> padding<10px> margin<10px>]:
	#div style[display<flex>]:
		#list:
		#list:
